---
title: "SIR_model"
author: "BZsofi"
date: '2019 március 22 '
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

FUNCTION DEFINITIONS
```{r}
SIR <- function(t, x, parms){
  with(as.list(c(parms,x)),{
    dS <- - beta*S*I
    dI <- + beta*S*I - r*I
    dR <- r*I
    der <- c(dS, dI,dR)
    list(der)
  })
}
```

MAIN PROGRAM - SIMULATION OF THE MODEL + PLOT
```{r, fig.width=6.5, fig.height=5}
library(deSolve)
library(ggplot2)

for(i in 1:5) {
  for(j in 1:5) {
parms <- c(beta=10^(-i), r=10^(-j+2))
inits <- c(S=499, I=1, R=0)
dt    <- seq(0,100,0.1)

N <- sum(inits)
R_0 <- with(as.list(parms),{beta*N/r})
title = paste("R_0 = ",R_0, sep = "")
beta = parms[1]
r = parms[2]
beta2 = paste("beta = ",beta, sep = "")
r2 = paste("r = ",r,sep = "")
subtitle = paste(beta2,r2, sep = ", ")

simulation <- as.data.frame(lsoda(inits, dt, SIR, parms=parms))

plot = ggplot(simulation, aes(x = time)) + 
      geom_line(aes(y = S, colour = "Susceptible"), size=3, alpha=0.45) + 
      geom_line(aes(y = I, colour = "Infected"), size=3.1, alpha=0.45) + 
      geom_line(aes(y = R, colour = "Recovered"), size=3.2, alpha=0.45) +
      ylab(label="Number of individuals") + 
      xlab("Time") +
      ggtitle(title, subtitle = subtitle) +
      scale_color_manual(name = " ",
        values = c("Susceptible" = "turquoise4", "Infected" = "tomato3", "Recovered" = "goldenrod2")) +
      theme(plot.background = element_rect(fill = "antiquewhite4"),
            legend.background = element_rect(fill = "antiquewhite4"),
            plot.title = element_text(size = 18, lineheight=.8, hjust=0.5, face="bold", colour="antiquewhite"),
            plot.subtitle = element_text(size = 16, lineheight=.8, hjust=0.5, face="italic", colour="antiquewhite"),
            axis.title = element_text(size = 15, face="bold",colour="antiquewhite"),
            axis.text = element_text(size = 12,colour="antiquewhite"),
            legend.position="top",
            legend.key = element_rect(fill = "seashell"),
            legend.text = element_text(size = 12,colour="antiquewhite"),
            legend.box.background = element_rect(colour = "antiquewhite", size=1.5),
            panel.background = element_rect(fill = "seashell", colour = "seashell", size = 0.5, linetype = "solid"),
            panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "antiquewhite"), 
            panel.grid.minor = element_line(size = 0.25, linetype = 'solid', colour = "antiquewhite"))
print(plot)
  }
}
```